### ISSUE TITLE
Error in `group_by()`

### ISSUE THREAD

**Issue by ghost** [CL-CHEN-Lab/Kronos_scRT#12]
Hello, Thanks for the nice single-cell RT pipeline. When I run the RT module of Kronos scRT, 

Kronos RT -F ./${project}/Kronos_RT/CNV/U2OS_10cells_NoAPH_per_Cell_summary_metrics.csv \
-T ./${project}/Kronos_RT/CNV/U2OS_cnv_calls.bed \
-C ./hg38_autosomal_sizes.tsv \
-o ./${project}/Kronos_RT/RT \
-b U2OS -f 200kb \
-S ./${project}/Kronos_RT/Diagnostic/U2OS_manual_settings.txt \
-c $cores -p -r chr1:10Mb-40Mb -R $RefRT -B 200000 --ref_name U2OS_Reference -N 3

I get the following error:

Error in `group_by()`:
! Must group by variables found in `.data`.
✖ Column `group` is not found.
Backtrace:
    ▆
 1. ├─RT_binning %>% group_by(group) %>% ...
 2. ├─dplyr::summarise(., Binning_step = min(Binning_step))
 3. ├─dplyr::group_by(., group)
 4. └─dplyr:::group_by.data.frame(., group)
 5.   └─dplyr::group_by_prepare(.data, ..., .add = .add, caller_env = caller_env())
 6.     └─rlang::abort(bullets, call = error_call)
 Execution has been stopped.

In the readme-files, it is mentioned that group names are the same as base_name. In my case, the base_name is "U2OS". Also, I tried mentioning group names using -g option but still I get the same error. Could you please let me know how to solve this error?

**Comment by josephides** [comment]
Hi @Jothivanan-Elumalai ,
The -b and -f options seem to be ok. It may be that there are not enough or no cells in S phase. Have you verified this with the diagnostic module plots ?

**Comment by josephides** [comment]
Issue closed due to inactivity.

**Comment by ghost** [comment]
Sorry, I completely forgot to respond. I had at least 14 samples in S-phase. My diagnostic plot was looking good (please find the attachment). I had a problem only when I started RT module. I am not sure if 14 is not enough. Anyway, thanks for your response.  
[test.pdf](https://github.com/CL-CHEN-Lab/Kronos_scRT/files/11207598/test.pdf)
