### ISSUE TITLE
Diagnosis & population RT

### ISSUE THREAD

**Issue by Romeo1-1** [CL-CHEN-Lab/Kronos_scRT#13]
Hello and thank you for this very interesting package !

I have an issue at the "diagnosis part". I'm trying to run Kronos on samples analyzed with 10x Genomics & CellRanger DNA. I tried with 3 different samples and get similar results

```
Kronos 10xtoKronos -F /mnt/h/xxx/per_cell_summary_metrics.csv -T /mnt/h/xxx/node_cnv_calls.bed -o xxx/Kronos_TestA
Kronos diagnostic -F TestA/Kronos_format_per_cell_summary_metrics.csv -o TestA/ --correct TRUE
```

When running with using `--correct TRUE` I get this error

```
Error in seq.default(range[1], range[2], length.out = self$detail) :
  'from' must be of length 1
Calls: suppressMessages ... <Anonymous> -> f -> <Anonymous> -> f -> seq -> seq.default
Execution halted
```

And I guess that's because Kronos doesn't detect any cells in S phase. When not using --correct TRUE, i get this kind of plot and each cells are tagged as "low coverage".

![Kronos](https://user-images.githubusercontent.com/101837631/189409774-f64612ff-e5e5-4ac1-bb22-8275aa3750d3.JPG)

This happened with 3 different samples from 3 different experiments. I played with the -m option to define a treshold, but what "treshold" would you recommend ? I set up -m at 40 and managed to identify some cells as phase S but that was purely randomly chosen. Also, I don't have data from FACS, should I let the other parameters as default ?

Thank you in advance

**Comment by Derfen3001** [comment]
Hello,

Yes, I think the error comes from the absence of S-phase cells. We do not suggest lowering the -m option below 117 for data obtained using the 10X genomics (you can check our paper Fig.1d for more details).

Based on the plot you posted I don't think that this sample is suitable for the analysis.

Best,

Stefano

**Comment by Romeo1-1** [comment]
After downsampling to -m 40 or -m 50, I identified some S-phase cells and could proceed to the next step. If you tell me that I shouldn't, then I will stop right there haha. Is there truly no way to use your package in that condition ? Anything below 117 reads/Mb isn't reliable enough ?

![image](https://user-images.githubusercontent.com/101837631/189457096-8292af3f-3aea-4042-8969-ceb7ec7da5af.png)

**Comment by Derfen3001** [comment]
Hey,

I don't think the calling in these cells is reliable, and even if it was, you don't have enough cells in S-phase. If you still have these samples, you could think about resequencing at a higher depth to call more cells and hopefully more cells in S-phase. If you want to further discuss you can write to me in private.

Best,

Stefano
